export const PLAY_POSITION = "PLAY_POSITION";
export const FETCH_STATE_BEGIN = "FETCH_STATE_BEGIN";
export const FETCH_STATE_SUCCESS = "FETCH_STATE_SUCCESS";
export const FETCH_STATE_FAILURE = "FETCH_STATE_FAILURE";
export const POST_STATE_SUCCESS = "POST_STATE_SUCCESS";
export const NEW_GAME = "NEW_GAME";
export const SAVE_GAME = "SAVE_GAME";
export const DELETE_GAME = "DELETE_GAME";