export const PLAY_POSITION = "PLAY_POSITION";
export const RESTART_GAME = "RESTART_GAME";
export const FETCH_STATE_BEGIN = "FETCH_STATE_BEGIN";
export const FETCH_STATE_SUCCESS = "FETCH_STATE_SUCCESS";
export const FETCH_STATE_FAILURE = "FETCH_STATE_FAILURE";
export const ADD_PLAYER = "ADD_PLAYER";